---
- hosts: tag_UbuntuDebian
  gather_facts: True
  become: yes
  
  roles:
    - { role: deploy_apache_centos, when: ansible_system == 'Linux' }
    
- hosts: tag_AmazonLinuxRedHat
  gather_facts: True
  become: yes
  
  roles:
    - { role: deploy_apache_centos, when: ansible_system == 'Linux' }