---
- name: Restart Httpd
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: Restart Apache2
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"